### ISSUE TITLE
Unable to include checkbox in the table

### ISSUE THREAD

**Issue by nag9329** [onechiporenko/ember-models-table#149]
I'm trying to include checkbox in template and making that template in one of the column as below. Below is the sample code of what I'm trying

columns: [
		{
			"title":"",
			"template":"component/select-box"
		},
		{
			"propertyName": "serverName",
			"title": "Server"
		}
]

I've a template named select-box in my templates/component folder which is rendering the checkbox when the table is loaded. But, when I select the checkbox, the checkbox does not display as checked.

component/select-box.hbs
<input type="checkbox" name="">

component/index.hbs
{{models-table data=model columns=columns}}

The checkbox was able show as checked in the previous version, but the latest version of ember-models-table has some issue it seems.

**Comment by onechiporenko** [comment]
Hi, @nag9329. Can you provide a demo on http://ember-twiddle.com? Thanks

**Comment by nag9329** [comment]
Hi @onechiporenko. Thanks for your quick response. Below is the url for twiddle
https://ember-twiddle.com/e986ba19649d8cb7d1903b4d9c6b075c?openFiles=templates.select-box.hbs%2C. The version that I used in the twiddle is 1.9.0, because I'm seeing some errors when I use the latest version. Even, with 1.9.0, when used the checkbox with actions on it, is producing the issue I was talking about. With 1.10.0, a simple checkbox with/without actions producing the issue. 

However, I want to use a checkbox with actions on it to send the selected row and it would be great if I've the option to select all / deselect all in the table header, which I don't know how to do that.

**Comment by onechiporenko** [comment]
@nag9329, I've published version `1.11.0-beta.1` with new features for templates and components for headers cells. I've done small example https://onechiporenko.github.io/ember-models-table/#/examples/select-rows-with-checkboxes for selection/deselection rows (commit https://github.com/onechiporenko/ember-models-table/commit/01c4e592d530bb7944c9762eaff6cd0a302c291b). 
Action `displayDataChanged` is used to get all selected items (check console logs in the demo).
I don't use real `input type="checkbox"` and use glyphicons to simulate them (columns dropdown is first item where you can see them). 
I hope this will hape you to solve your issue.

**Comment by nag9329** [comment]
@onechiporenko . Thanks a lot for your addition which makes my life easier. But, I still see a small problem I've downloaded the latest version and tried to use 

{{my-table-with-custom-header
  data=model
  columns=columns
  multipleSelect=true
  sendDisplayDataChangedAction=true}}

I'm getting the following error.  Assertion Failed: A helper named 'my-table-with-custom-header' could not be found. I see the version in the console as 1.10.3, but I'm using the latest version ans my package.json is having "ember-models-table":"1.11.0-beta.1".

**Comment by onechiporenko** [comment]
1. You have to extend `ember-models-table` and create your own component with action shown in the example.
2. Sometimes I forget to update version in vendor-script :(

**Comment by nag9329** [comment]
Never mind. I added my-table-with-custom-header.js file in my local add-on and exported in the app folder. Looks like everything is working. I'm closing this thread for now. I'll re-open if I see any issues in the latest build. Thanks again for your quick response and your valuable effort.
